#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config active_border_color '#c5c8c6'
bspc config normal_border_color '#2d2f34'

bspc config top_padding 30

bspc monitor -d I II III IV V

bar_alt &
xsetroot -cursor_name left_ptr
