#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

pkill -USR1 -x sxhkd
hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-e quit
hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-Shift-Return spawn urxvt -fn "*-lemon-*" -fb "*-lemon-*" -b 50

# hc keybind $Mod-F1 spawn urxvt -fn "xft:PragmataPro Mono:size=13" -fb "xft:PragmataPro Mono:style=bold:size=13"
# hc keybind $Mod-F2 spawn urxvt -fn "*-lemon-*" -fb "*-lemon-*" -b 50
# hc keybind $Mod-F3 spawn urxvt -fn "*-marathonmod-*" -fb "*-marathonmod-*"
# hc keybind $Mod-F4 spawn urxvt -fn "*-metis-*" -fb "*-metis-*"
# hc keybind $Mod-F5 spawn urxvt -fn "-nil-profont-medium-r-normal--12-120-72-72-c-60-iso8859-1" -fb "-nil-profont-medium-r-normal--12-120-72-72-c-60-iso8859-1"
# hc keybind $Mod-F6 spawn urxvt -fn "-*-neep-*-*-*-*-11-*-*-*-*-*-*-*" -fb "-*-neep-*-*-*-*-11-*-*-*-*-*-*-*"

hc keybind $Mod-F1 spawn urxvt -cd ~/doc/studium/uebungen_etc/2.bus
hc keybind $Mod-F2 spawn urxvt -cd ~/doc/studium/uebungen_etc/2.dsal
hc keybind $Mod-F3 spawn urxvt -cd ~/doc/studium/uebungen_etc/2.fosap
hc keybind $Mod-F4 spawn urxvt -cd ~/doc/studium/uebungen_etc/2.la

# hc keybind $Mod-d spawn run_dmenu
hc keybind $Mod-d spawn rofi -show run
hc keybind Print spawn screenie
hc keybind Shift-Print spawn screenie -s 
hc keybind $Mod-w spawn weefi
hc keybind $Mod-Shift-p spawn lock
hc keybind $Mod-t spawn tt
hc keybind $Mod-a spawn wmctrl -r :ACTIVE: -b toggle,above

# playback control
hc keybind $Mod-F6 spawn mpc prev
hc keybind $Mod-F7 spawn mpc toggle
hc keybind $Mod-F8 spawn mpc next
hc keybind $Mod-BackSpace spawn mpc seek 0%
hc keybind $Mod-y spawn mpc single

# vol control
hc keybind $Mod-F10 spawn vol !
hc keybind $Mod-F11 spawn vol -
hc keybind $Mod-F12 spawn vol +

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

hc keybind $Mod-Shift-g set window_gap 0
hc keybind $Mod-g set window_gap 10

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc mousebind $Mod-Button8 spawn mpc prev
hc mousebind $Mod-Button9 spawn mpc next


# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-n lock_tag
hc keybind $Mod-m unlock_tag
hc keybind $Mod-slash shift_to_monitor +1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#2d2f34'
hc set frame_border_normal_color '#c5c8c6'
hc set frame_bg_normal_color '#c5c8c6'
hc set frame_bg_active_color '#2d2f34'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color "$(getxrdb *.foreground)"
hc attr theme.normal.color "$(getxrdb *.color8)"
hc attr theme.urgent.color red
hc attr theme.inner_width 0
hc attr theme.inner_color '#2d2f34'
hc attr theme.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color '#2d2f34'
hc attr theme.active.inner_color "$(getxrdb *color0)"
hc attr theme.active.outer_color "$(getxrdb *color0)"
hc attr theme.background_color "$(getxrdb *foreground)"

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
mons -e top
hc detect_monitors

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" $monitor &
#done
# add an external panel
{
    pids=( )
    herbstclient pad 0 30
	herbstclient focus_monitor 0
    bar_alt &
    pids+=( $! )

    herbstclient pad 1 30
	herbstclient focus_monitor 1
    bar_alt &
    pids+=( $! )
    # wait until the panels should be stopped
    herbstclient -w '(quit_panel|reload)'
    # stopp all started panels
    kill ${pids[@]}
} &
